development:
  adapter:  postgresql
  encoding: utf8
  database: ilnar_test
  username: ilnar
  password: 104Hmoa)
  host:     localhost
  port:     5432
  pool:     10


test:
  database: db/test.sqlite3


